# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('ans1', models.CharField(max_length=50)),
                ('valid1', models.BooleanField(default=False)),
                ('ans2', models.CharField(max_length=50)),
                ('valid2', models.BooleanField(default=False)),
                ('ans3', models.CharField(max_length=50)),
                ('valid3', models.BooleanField(default=False)),
                ('ans4', models.CharField(max_length=50)),
                ('valid4', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Slave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('score', models.FloatField(default=0)),
            ],
        ),
    ]
