# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 20:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans1', models.CharField(max_length=50)),
                ('valid1', models.BooleanField(default=False)),
                ('ans2', models.CharField(max_length=50)),
                ('valid2', models.BooleanField(default=False)),
                ('ans3', models.CharField(max_length=50)),
                ('valid3', models.BooleanField(default=False)),
                ('ans4', models.CharField(max_length=50)),
                ('valid4', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('question_type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Slave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('phone_number', models.CharField(default='/', max_length=20)),
                ('year_of_study', models.IntegerField(default=None)),
                ('email', models.EmailField(default=None, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='SlaveAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slave_answer_text', models.TextField(blank=True, default=None, max_length=200)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kviz.Question')),
                ('slave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kviz.Slave')),
            ],
        ),
        migrations.AddField(
            model_name='answercheck',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kviz.Question'),
        ),
    ]
