# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kviz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subordinate',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
